Repository FRONTENDSCHOOL8/Karly, pull requests merged in 2024-01, with the labels that each got.

#61 [add] main 페이지 최근 본 상품 목록 swiper.js 기능 구현
  index.html
  main.js
  src/styles/main.css
Labels: feature

#62 [add] 제품 상세 페이지 CSS 완료, 마크업 일부 수정, notify 아이콘 삭제
  .gitignore
  src/assets/icons/notify.png
  src/pages/product_detail/index.html
  src/pages/product_detail/product_detail.css
Labels: in progress

#63 [add] 제품 상세 페이지 수량 추가/제거 기능 및 가격 연동 기능 구현
  package-lock.json
  package.json
  pocketbase/pb_data/logs.db
  src/pages/product_detail/index.html
  src/pages/product_detail/product_detail.css
  src/pages/product_detail/product_detail.js
Labels: feature

#65 [modify] main 페이지 상품 대체 텍스트 수정
  index.html
Labels: enhancement, feature

#67 [modify] 헤더 컴포넌트 카테고리 아이콘 대체 텍스트 적용 및 링크 연결
  src/components/header/header.css
  src/components/header/index.html
Labels: enhancement, feature

#68 [add] 제품 상세 페이지 찜 버튼 클릭 시 UI 변경 기능, '장바구니 담기' 버튼 클릭 시 담기 완료 안내 버블 생성 및 삭제 기능 구현
  src/assets/icons/pointed_cart_bubble_element.png
  src/pages/product_detail/index.html
  src/pages/product_detail/product_detail.css
  src/pages/product_detail/product_detail.js
Labels: feature

#70 [add] localStorage 객체 초기화 setDefaultData 공통 모듈 추가
  src/lib/utils/index.js
  src/lib/utils/setDefaultData.js
Labels: feature

#104 [modify] /lib/dom/checkLogin.js 삭제
  src/lib/dom/checkLogin.js
  src/lib/dom/index.js
Labels: enhancement

#106 [modify] merge 병합 오류 - getPbImageURL.js
  src/lib/utils/getPbImageURL.js
Labels: duplicate

#112 [modify] 로그인 시 최근 본 상품 목록 초기화
  src/pages/login/login.js
Labels: enhancement

#120 [modify] swiper, pocketbase 랜더링 순서로 인한 버그 개선
  main.js
Labels: bug
